import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useRef, useState } from 'react'
import {BrowserQRCodeReader} from '@zxing/browser'

import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  const videoRef = useRef<HTMLVideoElement>(null)

  const [data, setData] = useState('Not found')

  useEffect(() => {
    (async () => {
      if (videoRef.current) {
        const videoStream = await navigator.mediaDevices.getUserMedia({ video: true })

        videoRef.current.srcObject = videoStream

        const codeReader = new BrowserQRCodeReader()
        
        await codeReader.decodeFromVideoElement(videoRef.current, (value, error, controls) => {
          console.log(value)
          if (!value?.getText()) {
            return
          }
          console.log(value)
          setData(value?.getText())
          controls.stop()
        })
      }
    })()
  }, [])
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <video autoPlay ref={videoRef} /> 
        <p>{data}</p>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
